(function(){'use strict';
const SUPABASE_URL='https://yhspipyrgdcdfqqxxges.supabase.co';
const SUPABASE_KEY='sb_publishable_IcyDHTLjyPPspvcgnYZZiw_q1lUn8QW';
const API='https://kajim-ai-agent-backend.onrender.com';
function loadSdk(){return new Promise((resolve,reject)=>{if(window.supabase?.createClient)return resolve();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.116.0/dist/umd/supabase.min.js';s.onload=resolve;s.onerror=()=>reject(new Error('Supabase SDK লোড হয়নি'));document.head.appendChild(s);});}
function esc(v){return String(v||'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));}
async function init(){await loadSdk();const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);window.akexaSupabase=sb;const style=document.createElement('style');style.textContent='#akexa-auth{position:fixed;inset:0;z-index:9999;background:rgba(5,5,12,.96);display:flex;align-items:center;justify-content:center;padding:20px;font-family:Inter,Arial,sans-serif}#akexa-auth .box{width:100%;max-width:390px;background:#121222;border:1px solid #353550;border-radius:18px;padding:26px;box-shadow:0 15px 60px #0008}#akexa-auth h2{margin:0 0 8px;color:#f0f0ff}#akexa-auth p{color:#aaaac0;font-size:13px;line-height:1.6}#akexa-auth input{width:100%;box-sizing:border-box;margin:7px 0;padding:12px;border-radius:9px;border:1px solid #353550;background:#202034;color:#fff}#akexa-auth button{width:100%;margin-top:10px;padding:12px;border:0;border-radius:9px;background:linear-gradient(135deg,#6c63ff,#a855f7);color:#fff;font-weight:700;cursor:pointer}#akexa-auth .switch{background:transparent;border:1px solid #353550;color:#c4bdff}#akexa-auth .msg{font-size:12px;color:#fbbf24;min-height:18px;margin-top:10px}#akexa-user{display:flex;align-items:center;gap:8px;font-size:12px;color:#c4bdff}#akexa-user button{border:1px solid #353550;background:transparent;color:#aaaac0;border-radius:8px;padding:6px 9px;cursor:pointer}';document.head.appendChild(style);
let auth=document.getElementById('akexa-auth');if(!auth){auth=document.createElement('div');auth.id='akexa-auth';auth.innerHTML='<div class="box"><h2>AKEXA AI Bazar</h2><p id="akexa-auth-sub">Login করুন অথবা নতুন অ্যাকাউন্ট তৈরি করুন।</p><input id="akexa-email" type="email" placeholder="Email address"><input id="akexa-password" type="password" placeholder="Password (কমপক্ষে ৬ অক্ষর)"><button id="akexa-auth-submit">Login</button><button id="akexa-auth-switch" class="switch">নতুন অ্যাকাউন্ট তৈরি করুন</button><div id="akexa-auth-msg" class="msg"></div></div>';document.body.appendChild(auth)}
const email=auth.querySelector('#akexa-email'),password=auth.querySelector('#akexa-password'),submit=auth.querySelector('#akexa-auth-submit'),switchBtn=auth.querySelector('#akexa-auth-switch'),msg=auth.querySelector('#akexa-auth-msg');let signup=false;
function message(t,error){msg.textContent=t;msg.style.color=error?'#ff8080':'#fbbf24';}
function renderUser(user){let el=document.getElementById('akexa-user');if(!el){el=document.createElement('div');el.id='akexa-user';const top=document.querySelector('.topbar-right')||document.querySelector('.topbar');if(top)top.prepend(el);else document.body.appendChild(el)}if(user){el.innerHTML='<span>👤 '+esc(user.email)+'</span><button id="akexa-logout">Logout</button>';el.querySelector('#akexa-logout').onclick=()=>sb.auth.signOut();}else el.remove();}
async function refresh(){const {data}=await sb.auth.getSession();if(data.session){auth.style.display='none';renderUser(data.session.user);window.akexaSession=data.session;return true;}auth.style.display='flex';return false;}
switchBtn.onclick=()=>{signup=!signup;submit.textContent=signup?'Sign up':'Login';switchBtn.textContent=signup?'আগের অ্যাকাউন্ট দিয়ে Login':'নতুন অ্যাকাউন্ট তৈরি করুন';auth.querySelector('#akexa-auth-sub').textContent=signup?'নতুন AKEXA AI Bazar অ্যাকাউন্ট তৈরি করুন।':'Login করুন অথবা নতুন অ্যাকাউন্ট তৈরি করুন।';message('');};
submit.onclick=async()=>{const e=email.value.trim(),p=password.value;if(!e||!p)return message('Email ও password দিন',true);submit.disabled=true;message('প্রসেসিং...');try{const result=signup?await sb.auth.signUp({email:e,password:p}):await sb.auth.signInWithPassword({email:e,password:p});if(result.error)throw result.error;if(signup&&!result.data.session){message('ইমেইলে confirmation link পাঠানো হয়েছে। ইমেইল verify করুন।');}else{message('সফলভাবে Login হয়েছে।');await refresh();}}catch(err){message(err.message||'Authentication failed',true);}finally{submit.disabled=false;}};
sb.auth.onAuthStateChange((_event,session)=>{window.akexaSession=session;if(session){auth.style.display='none';renderUser(session.user);}else{auth.style.display='flex';renderUser(null);}});
window.fetch=(()=>{const original=window.fetch;return function(input,init){init=init||{};const u=typeof input==='string'?input:input.url;if(u&&u.startsWith(API)){const token=window.akexaSession?.access_token;if(token){init.headers=Object.assign({},init.headers||{}, {Authorization:'Bearer '+token});}}return original.call(this,input,init);};})();
await refresh();}
init().catch(err=>console.error('[AKEXA AUTH]',err));
})();