// AKEXA Website Chat Widget — paste this script into any website.
(function(){
  const script=document.currentScript;
  const agentId=(script&&script.dataset&&script.dataset.agentId)||new URL(script?.src||location.href).searchParams.get('agentId');
  const API=(script&&script.dataset&&script.dataset.api)||'https://kajim-ai-agent-backend.onrender.com';
  if(!agentId){console.warn('AKEXA Widget: data-agent-id is required');return;}
  const sidKey='akexa_widget_session_'+agentId;
  let sessionId=localStorage.getItem(sidKey)||'';
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  const style=document.createElement('style');style.textContent='.akexa-w{position:fixed;right:20px;bottom:20px;z-index:2147483647;font-family:Arial,sans-serif}.akexa-b{width:58px;height:58px;border:0;border-radius:50%;cursor:pointer;font-size:25px;background:#111;color:#f4c76a;box-shadow:0 8px 28px #0005}.akexa-p{display:none;flex-direction:column;width:340px;height:480px;background:#fff;border-radius:18px;box-shadow:0 12px 45px #0004;overflow:hidden}.akexa-h{padding:15px;background:#111;color:#fff;font-weight:700}.akexa-m{flex:1;padding:14px;overflow:auto;background:#f6f6f6}.akexa-msg{margin:8px 0;padding:10px 12px;border-radius:13px;max-width:82%;white-space:pre-wrap;line-height:1.4}.akexa-u{margin-left:auto;background:#111;color:#fff}.akexa-a{background:#fff;border:1px solid #ddd}.akexa-f{display:flex;padding:10px;border-top:1px solid #ddd;gap:8px}.akexa-i{flex:1;padding:11px;border:1px solid #ccc;border-radius:12px}.akexa-s{border:0;border-radius:12px;padding:0 14px;background:#111;color:#fff}.akexa-open .akexa-b{display:none}.akexa-open .akexa-p{display:flex}@media(max-width:480px){.akexa-p{width:calc(100vw - 24px);height:70vh}.akexa-w{right:12px;bottom:12px}}';document.head.appendChild(style);
  const root=document.createElement('div');root.className='akexa-w';root.innerHTML='<button class="akexa-b" aria-label="Open chat">💬</button><div class="akexa-p"><div class="akexa-h">AI Assistant <span style="float:right;cursor:pointer" class="akexa-x">×</span></div><div class="akexa-m"><div class="akexa-msg akexa-a">হ্যালো! কীভাবে সাহায্য করতে পারি?</div></div><form class="akexa-f"><input class="akexa-i" placeholder="আপনার প্রশ্ন লিখুন…" autocomplete="off"><button class="akexa-s">Send</button></form></div>';document.body.appendChild(root);
  const box=root.querySelector('.akexa-m'),input=root.querySelector('.akexa-i'),form=root.querySelector('.akexa-f');root.querySelector('.akexa-b').onclick=()=>root.classList.add('akexa-open');root.querySelector('.akexa-x').onclick=()=>root.classList.remove('akexa-open');
  function add(text,who){const d=document.createElement('div');d.className='akexa-msg '+(who==='u'?'akexa-u':'akexa-a');d.textContent=text;box.appendChild(d);box.scrollTop=box.scrollHeight;}
  form.onsubmit=async e=>{e.preventDefault();const message=input.value.trim();if(!message)return;add(message,'u');input.value='';add('…','a');const wait=box.lastChild;try{const r=await fetch(API+'/widget/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agentId,message,sessionId})});const d=await r.json();wait.remove();if(d.sessionId){sessionId=d.sessionId;localStorage.setItem(sidKey,sessionId)}add(d.reply||d.error||'দুঃখিত, উত্তর পাওয়া যায়নি।','a')}catch(err){wait.remove();add('সংযোগে সমস্যা হয়েছে।','a')}};
})();
